version: "3.8"
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # server:
  #   build: .
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - db

volumes:
  pgdata:
